// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx0kBmkylZRHTVLvgf7rjwRjyb_ZvIgYE',
    appId: '1:86238156804:web:25570724a16723863fbd51',
    messagingSenderId: '86238156804',
    projectId: 'ruumies-517e2',
    authDomain: 'ruumies-517e2.firebaseapp.com',
    storageBucket: 'ruumies-517e2.firebasestorage.app',
    measurementId: 'G-ML8D8GSWXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFuZqHLI9Gr_VmwKi8NhUS9Zyp9PJxZZw',
    appId: '1:86238156804:android:ca54acc6025616c43fbd51',
    messagingSenderId: '86238156804',
    projectId: 'ruumies-517e2',
    storageBucket: 'ruumies-517e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWhcxqxle8pJb0pvU03Rm4GuWmh0_a87s',
    appId: '1:86238156804:ios:466f872b2918d2a63fbd51',
    messagingSenderId: '86238156804',
    projectId: 'ruumies-517e2',
    storageBucket: 'ruumies-517e2.firebasestorage.app',
    iosClientId: '86238156804-987ebs1hfk54p2mff9k4npqu6onuhbjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruumiesAlpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWhcxqxle8pJb0pvU03Rm4GuWmh0_a87s',
    appId: '1:86238156804:ios:466f872b2918d2a63fbd51',
    messagingSenderId: '86238156804',
    projectId: 'ruumies-517e2',
    storageBucket: 'ruumies-517e2.firebasestorage.app',
    iosClientId: '86238156804-987ebs1hfk54p2mff9k4npqu6onuhbjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruumiesAlpha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx0kBmkylZRHTVLvgf7rjwRjyb_ZvIgYE',
    appId: '1:86238156804:web:843abc8e53cf72d33fbd51',
    messagingSenderId: '86238156804',
    projectId: 'ruumies-517e2',
    authDomain: 'ruumies-517e2.firebaseapp.com',
    storageBucket: 'ruumies-517e2.firebasestorage.app',
    measurementId: 'G-TL2R5VERJG',
  );
}
